name: test_hyperhire
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1
  outline_gradient_button: ^2.0.1+1
  smooth_page_indicator: ^1.2.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  freezed_annotation: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/


